### ISSUE TITLE
Stuck "waiting for welcome message"... again

### ISSUE THREAD

**Issue by swatt6400** [bolcom/libunftp#235]
I just upgraded to the latest FileZilla.  Getting this issue against every site I have.

It's identical to: [this issue](https://github.com/bolcom/libunftp/issues/109)

I downloaded Core FTP, and the same site works instantly.  So I'd say it's an issue in FileZilla.

**Comment by hannesdejager** [comment]
Hi @swatt6400, do you run libunftp based FTP servers on you sites you mentioned?

**Comment by swatt6400** [comment]
Hi there, interesting.  I use SmarterASP.net hosing for my sites. 
    I've asked them what FTP server they use, and hopefully we get a
    reply.  Obviously, I won't be able to make any server-side changes
    to FTP.  Filezilla used to work fine with SmarterASP for many many
    years.  Thanks!
    
    On 7/10/2020 3:21 PM, Hannes de Jager
      wrote:
    
    
      
      Hi @swatt6400,
        do you run libunftp based FTP servers on you sites you
        mentioned?
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bolcom/libunftp/issues/235#issuecomment-656816824",
"url": "https://github.com/bolcom/libunftp/issues/235#issuecomment-656816824",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by swatt6400** [comment]
Hi, ok, the response from the FTP server is "Serv-U FTP Server v15.1 ready".   Hopefully that lets you know the FTP Server software.

The provider did some testing and Filezilla works for them, and with TLS too.  Although the conversation looks a bit different.  There's no "AUTH TLS" row.
![image](https://user-images.githubusercontent.com/17034491/87305120-570cbd00-c4ec-11ea-932f-3b5ac423786a.png)

Yes, I noticed they resolve a different IP for the FTP server, and I tried going against that one, but the result is the same.

I discovered mine works if I use Plain Text for Encryption, but not with any of the other options.  I think it's breaking down at AUTH TLS.
![image](https://user-images.githubusercontent.com/17034491/87304683-91c22580-c4eb-11ea-8144-a0a5c2186e24.png)

Having discovered that, I see that CoreFTP also cannot connect with AUTH TLS.

I'm on the latest version (3.48.1), but I've asked them their version, since they can connect and I can't.

**Comment by hannesdejager** [comment]
Hi @swatt6400. The provider that did the tests seems to have used certificate based TLS authentication whereas you probably testing normal username / password based TLS authentication. I suggest you ask your provider to test the latter.

Since the server software is not libunftp based, this ticket is of course not relevant for libunftp anymore. We used to have this issue in libunftp due to internal deadlocks but we believe we resolved it. I suggest you log a ticket with FileZilla support instead: https://filezilla-project.org/support.php or of course like mentioned talk to your FTP provider. Perhaps they even want to try https://github.com/bolcom/unFTP :-).

I'll close this ticket now.
